In [2]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import pandas as pd


In [4]:
df = pd.read_csv('Galaxy_Data_-_All_Galaxies.csv')

In [5]:
df

OBJID          RA        DEC  \
0      5.880180e+17  218.580808   8.161055   
1      5.877300e+17  239.931122   3.644782   
2      5.877242e+17   10.641342  15.445178   
3      5.877415e+17  165.379954  28.187846   
4      5.877300e+17  216.307612  -1.099459   
...             ...         ...        ...   
19995  5.877334e+17  231.967240  50.455685   
19996  5.880177e+17  243.777330   6.092806   
19997  5.877250e+17  184.644965  -1.598657   
19998  5.877258e+17  118.714675  45.705057   
19999  5.880177e+17  173.612528  12.493277   

                                                 IMG_URL  REDSHIFT  \
0      http://skyserver.sdss.org/dr12/en/tools/explor...  0.053766   
1      http://skyserver.sdss.org/dr12/en/tools/explor...  0.054367   
2      http://skyserver.sdss.org/dr12/en/tools/explor...  0.079503   
3      http://skyserver.sdss.org/dr12/en/tools/explor...  0.069913   
4      http://skyserver.sdss.org/dr12/en/tools/explor...  0.055574   
...                                                  ...       ...   
19995  http://skyserver.sdss.org/dr12/en/tools/explor...  0.073404   
19996  http://skyserver.sdss.org/dr12/en/tools/explor...  0.059610   
19997  http://skyserver.sdss.org/dr12/en/tools/explor...  0.079722   
19998  http://skyserver.sdss.org/dr12/en/tools/explor...  0.052579   
19999  http://skyserver.sdss.org/dr12/en/tools/explor...  0.079053   

       P_ELLIPTICAL  P_SPIRAL       UMAG       GMAG       RMAG       IMAG  \
0          0.530869  0.437261 -18.684864 -20.204231 -20.955414 -21.298212   
1          0.000000  0.961538 -20.101736 -21.384073 -21.838770 -21.980230   
2          0.470876  0.491672 -19.834967 -21.217686 -21.850147 -22.147160   
3          0.532013  0.424623 -19.435511 -20.811283 -21.509943 -21.847149   
4          0.647059  0.088235 -18.376757 -19.623747 -20.199842 -20.470566   
...             ...       ...        ...        ...        ...        ...   
19995      0.946228  0.019281 -19.803755 -21.573761 -22.339725 -22.708660   
19996      0.758621  0.000000 -16.315529 -20.404915 -21.282505 -21.124458   
19997      0.129100  0.562271 -19.415325 -20.450088 -20.837673 -20.960474   
19998      0.837452  0.064308 -19.477306 -21.262995 -22.042334 -22.473787   
19999      0.847757  0.132819 -18.893919 -20.679129 -21.359232 -21.659225   

            ZMAG   LOG_MASS  R90_ARCSEC  AXIAL_RATIO  LOCAL_DENSITY  \
0     -21.558670  10.516412    6.294165     0.368354        -0.1800   
1     -22.158155  10.592430   14.513707     0.799851        -0.2080   
2     -22.348995  10.828524    7.862754     0.879052         0.8070   
3     -22.106108  10.672685    6.840029     0.930676         0.0285   
4     -20.681120   9.964785    3.187091     0.831526         0.1040   
...          ...        ...         ...          ...            ...   
19995 -22.984587  11.098833    8.970359     0.721744        -0.5390   
19996 -22.213829  11.365675   13.147679     0.741964        -0.5400   
19997 -21.146212  10.002666    5.776074     0.621813        -0.6670   
19998 -22.752541  10.986648   11.711008     0.841293         1.4600   
19999 -21.890398  10.662863    6.333528     0.915966        -0.4550   

       NEARCLUSTER_DIST  NEARCLUSTER_MASS    G-R  
0           -999.000000     -9.990000e+02  0.751  
1             15.959925      5.430000e+12  0.455  
2              1.059320      3.940000e+14  0.632  
3           -999.000000     -9.990000e+02  0.699  
4             11.604042      3.740000e+13  0.576  
...                 ...               ...    ...  
19995         12.696922      1.450000e+14  0.766  
19996       -999.000000     -9.990000e+02  0.878  
19997         19.389032      6.630000e+14  0.388  
19998          0.000000      8.510000e+13  0.779  
19999          8.063866      1.560000e+14  0.680  

[20000 rows x 19 columns]

In [7]:
mass = np.array(df['LOG_MASS'])

In [8]:
mass

array([10.51641178, 10.59243011, 10.82852364, ..., 10.00266552,
       10.98664761, 10.66286278])

In [19]:
m = 10**mass


In [20]:
mass_df = pd.DataFrame(m)

In [21]:
mass_df

0
0      3.284065e+10
1      3.912282e+10
2      6.737886e+10
3      4.706355e+10
4      9.221140e+09
...             ...
19995  1.255547e+11
19996  2.320999e+11
19997  1.006156e+10
19998  9.697228e+10
19999  4.601112e+10

[20000 rows x 1 columns]

In [24]:
mass_df.to_csv("mass.csv", index = False)

In [25]:
df1 = pd.read_csv('Spirals.csv')

In [26]:
df1

OBJID          RA        DEC  \
0     5.877300e+17  239.931122   3.644782   
1     5.880180e+17  199.705642  39.656256   
2     5.877336e+17  252.147662  35.160900   
3     5.877325e+17  126.812745  31.878147   
4     5.880180e+17  237.891611  27.370528   
...            ...         ...        ...   
6876  5.877319e+17  176.727306  55.395927   
6877  5.877381e+17  121.589235  53.069495   
6878  5.877258e+17  224.903804  63.024535   
6879  5.877378e+17  123.219860  51.834880   
6880  5.877366e+17  246.281627  24.261226   

                                                IMG_URL  REDSHIFT  \
0     http://skyserver.sdss.org/dr12/en/tools/explor...  0.054367   
1     http://skyserver.sdss.org/dr12/en/tools/explor...  0.073667   
2     http://skyserver.sdss.org/dr12/en/tools/explor...  0.081899   
3     http://skyserver.sdss.org/dr12/en/tools/explor...  0.050641   
4     http://skyserver.sdss.org/dr12/en/tools/explor...  0.075346   
...                                                 ...       ...   
6876  http://skyserver.sdss.org/dr12/en/tools/explor...  0.084341   
6877  http://skyserver.sdss.org/dr12/en/tools/explor...  0.064056   
6878  http://skyserver.sdss.org/dr12/en/tools/explor...  0.062280   
6879  http://skyserver.sdss.org/dr12/en/tools/explor...  0.082570   
6880  http://skyserver.sdss.org/dr12/en/tools/explor...  0.056721   

      P_ELLIPTICAL  P_SPIRAL       UMAG       GMAG       RMAG       IMAG  \
0         0.000000  0.961538 -20.101736 -21.384073 -21.838770 -21.980230   
1         0.048301  0.900944 -18.862560 -19.903929 -20.430437 -20.662457   
2         0.012419  0.886366 -19.107744 -20.059378 -20.346416 -20.392763   
3         0.000000  0.963636 -18.912079 -19.849363 -20.213543 -20.329000   
4         0.015887  0.984113 -18.998379 -20.511614 -21.290276 -21.690281   
...            ...       ...        ...        ...        ...        ...   
6876      0.018444  0.948221 -19.307405 -20.372234 -20.854553 -21.050100   
6877      0.000000  1.000000 -19.219717 -20.649479 -21.221235 -21.350328   
6878      0.070927  0.929073 -19.123232 -20.360298 -20.978498 -21.295471   
6879      0.152730  0.800564 -18.361580 -19.893032 -20.646530 -21.015867   
6880      0.076705  0.923295 -19.193216 -20.265034 -20.759535 -20.958372   

           ZMAG   LOG_MASS  R90_ARCSEC  AXIAL_RATIO  LOCAL_DENSITY  \
0    -22.158155  10.592430   14.513707     0.799851        -0.2080   
1    -20.761246   9.991632    5.766130     0.397562        -0.6720   
2    -20.432737   9.817999    6.654042     0.842881        -0.7110   
3    -20.468565   9.781473    8.606720     0.381173        -0.5820   
4    -21.980810  10.662916    9.667852     0.225967         0.0354   
...         ...        ...         ...          ...            ...   
6876 -21.058376  10.323669    8.278441     0.265907        -0.5060   
6877 -21.422647  10.439681   11.536574     0.660463         0.0668   
6878 -21.539459  10.436174    6.598935     0.550022        -0.6070   
6879 -21.335882  10.399365    3.994223     0.446672        -0.5270   
6880 -21.088922  10.146765    7.424337     0.377744         0.2970   

      NEARCLUSTER_DIST  NEARCLUSTER_MASS    G-R  
0            15.959925      5.430000e+12  0.455  
1             7.014873      5.760000e+14  0.527  
2            16.788237      1.020000e+15  0.287  
3             5.484953      3.250000e+14  0.364  
4             5.416655      3.730000e+14  0.779  
...                ...               ...    ...  
6876         24.801096      7.590000e+13  0.482  
6877         26.448175      2.050000e+14  0.572  
6878         40.749893      1.580000e+15  0.618  
6879         27.341381      8.170000e+13  0.753  
6880         19.719330      9.140000e+13  0.495  

[6881 rows x 19 columns]

In [29]:
mass1 = np.array(df1['LOG_MASS'])

In [30]:
mass1

array([10.59243011,  9.99163151,  9.81799889, ..., 10.43617439,
       10.39936543, 10.14676476])

In [31]:
m1 = 10**mass1

In [32]:
m1

array([3.91228163e+10, 9.80915303e+09, 6.57656156e+09, ...,
       2.73007382e+10, 2.50821887e+10, 1.40205406e+10])

In [33]:
mass1_df = pd.DataFrame(m1)

In [34]:
mass1_df

0
0     3.912282e+10
1     9.809153e+09
2     6.576562e+09
3     6.046070e+09
4     4.601678e+10
...            ...
6876  2.107024e+10
6877  2.752207e+10
6878  2.730074e+10
6879  2.508219e+10
6880  1.402054e+10

[6881 rows x 1 columns]

In [36]:
mass1_df.to_csv("spiral_mass.csv", index = False)

In [37]:
df2 = pd.read_csv('Ellipticals.csv')
df2

OBJID          RA        DEC  \
0     5.877269e+17  337.154074  -9.767217   
1     5.877294e+17  127.522598  43.759190   
2     5.880155e+17   16.453773  -1.149316   
3     5.877315e+17   46.979240  -0.946646   
4     5.877417e+17  150.082461  22.037433   
...            ...         ...        ...   
2504  5.877394e+17  134.348028  24.237455   
2505  5.880180e+17  219.314108   7.755419   
2506  5.877334e+17  231.967240  50.455685   
2507  5.877258e+17  118.714675  45.705057   
2508  5.880177e+17  173.612528  12.493277   

                                                IMG_URL  REDSHIFT  \
0     http://skyserver.sdss.org/dr12/en/tools/explor...  0.054510   
1     http://skyserver.sdss.org/dr12/en/tools/explor...  0.083467   
2     http://skyserver.sdss.org/dr12/en/tools/explor...  0.064887   
3     http://skyserver.sdss.org/dr12/en/tools/explor...  0.066651   
4     http://skyserver.sdss.org/dr12/en/tools/explor...  0.082611   
...                                                 ...       ...   
2504  http://skyserver.sdss.org/dr12/en/tools/explor...  0.065360   
2505  http://skyserver.sdss.org/dr12/en/tools/explor...  0.059434   
2506  http://skyserver.sdss.org/dr12/en/tools/explor...  0.073404   
2507  http://skyserver.sdss.org/dr12/en/tools/explor...  0.052579   
2508  http://skyserver.sdss.org/dr12/en/tools/explor...  0.079053   

      P_ELLIPTICAL  P_SPIRAL       UMAG       GMAG       IMAG       ZMAG  \
0         0.916667  0.000000 -18.564734 -20.278315 -21.364716 -21.586166   
1         0.812509  0.069556 -19.757879 -21.485485 -22.577099 -22.799059   
2         0.896151  0.069091 -19.394754 -21.085913 -22.217220 -22.457973   
3         0.879150  0.103900 -18.883778 -20.505205 -21.583267 -21.844299   
4         0.841372  0.127261 -19.414875 -21.110426 -22.237358 -22.514736   
...            ...       ...        ...        ...        ...        ...   
2504      1.000000  0.000000 -19.076828 -20.643663 -21.645475 -21.869448   
2505      0.857143  0.063492 -18.827198 -20.372269 -21.248264 -21.420326   
2506      0.946228  0.019281 -19.803755 -21.573761 -22.708660 -22.984587   
2507      0.837452  0.064308 -19.477306 -21.262995 -22.473787 -22.752541   
2508      0.847757  0.132819 -18.893919 -20.679129 -21.659225 -21.890398   

       LOG_MASS  R90_ARCSEC  AXIAL_RATIO  LOCAL_DENSITY  NEARCLUSTER_DIST  \
0     10.551561    9.176252     0.840303         0.4760         28.022841   
1     11.030069    6.707622     0.792731         0.2200         39.925865   
2     10.899630   10.792054     0.898537         0.1120          2.647391   
3     10.630261    5.009472     0.679815        -0.7760         67.197342   
4     10.912819    7.424716     0.896945        -0.8460       -999.000000   
...         ...         ...          ...            ...               ...   
2504  10.654794    6.186992     0.888195        -0.6880         43.161980   
2505  10.484015    5.428783     0.897203        -0.0607       -999.000000   
2506  11.098833    8.970359     0.721744        -0.5390         12.696922   
2507  10.986648   11.711008     0.841293         1.4600          0.000000   
2508  10.662863    6.333528     0.915966        -0.4550          8.063866   

      NEARCLUSTER_MASS    G-R  
0         4.570000e+14  0.740  
1         1.540000e+14  0.735  
2         1.240000e+14  0.770  
3         1.710000e+14  0.740  
4        -9.990000e+02  0.775  
...                ...    ...  
2504      1.200000e+14  0.710  
2505     -9.990000e+02  0.636  
2506      1.450000e+14  0.766  
2507      8.510000e+13  0.779  
2508      1.560000e+14  0.680  

[2509 rows x 18 columns]

In [39]:
mass2 = np.array(df2['LOG_MASS'])
mass2

array([10.55156136, 11.03006935, 10.89962959, ..., 11.09883308,
       10.98664761, 10.66286278])

In [40]:
m2 = 10**mass2

In [41]:
m2

array([3.56091297e+10, 1.07169042e+11, 7.93651041e+10, ...,
       1.25554730e+11, 9.69722807e+10, 4.60111174e+10])

In [42]:
mass2_df = pd.DataFrame(m2)

In [44]:
mass2_df

0
0     3.560913e+10
1     1.071690e+11
2     7.936510e+10
3     4.268364e+10
4     8.181236e+10
...            ...
2504  4.516414e+10
2505  3.048003e+10
2506  1.255547e+11
2507  9.697228e+10
2508  4.601112e+10

[2509 rows x 1 columns]

In [45]:
mass2_df.to_csv("elliptical_mass.csv", index = False)